version: "3"

services:
    tid-backend:
        container_name: tid-backend
        build:
            context: "./backend"
        restart: unless-stopped
        environment:
            - DBHOST=tid-db
            - DB=tid
            - DBUSER=${DBUSER}
            - DBPASS=${DBPASS}
    tid-frontend:
        container_name: tid-frontend
        volumes:
            - ./frontend/dist:/srv/dist
        build:
            context: "./frontend"
    tid-db:
        container_name: tid-db
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mariadb-init.sql:/docker-entrypoint-initdb.d/1.sql
        environment:
            - MYSQL_DATABASE=tid
            - MYSQL_ROOT_PASSWORD=${ROOTPASS}
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}
    tid-webserver:
        container_name: tid-nginx
        image: nginx
        ports:
            - "5001:80"
        volumes:
            - ./default-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist/:/usr/share/nginx/html/

networks:
    default:
        external: false
        name: "tid-network"
