version: "3"

services:
    tid-backend:
        container_name: tid-backend
        build:
            context: "./backend"
        ports:
            - "7676:7676"
        restart: unless-stopped
        environment:
            - DBHOST=tid-db
            - DB=tid
            - DBUSER=${DBUSER}
            - DBPASS=${DBPASS}
    tid-frontend:
        container_name: tid-frontend
        build:
            context: "./frontend"
        ports:
            - "5001:8080"
    tid-db:
        container_name: tid-db
        image: mysql
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mariadb-init.sql:/docker-entrypoint-initdb.d/1.sql
        environment:
            - MYSQL_DATABASE=tid
            - MYSQL_ROOT_PASSWORD=${ROOTPASS}
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}

networks:
    default:
        external: false
        name: "tid-network"
